- hosts: db
  tasks:
    - name: Backup Ambari Schema
      shell: mysqldump -u root --password={{ password }} --databases {{ db_ambari_name }} > {{ mysql_backup_dir }}/{{ db_ambari_name }}.`date +%Y-%m-%d_%H-%M-%S`.sql
    - name: Backup Hive Schema
      shell: mysqldump -u root --password={{ password }} --databases {{ db_hive_name }} > {{ mysql_backup_dir }/{{ db_hive_name }}.`date +%Y-%m-%d_%H-%M-%S`.sql
    - name: Backup Oozie Schema
      shell: mysqldump -u root --password={{ password }} --databases {{ db_oozie_name }} > {{ mysql_backup_dir }/{{ db_oozie_name }}.`date +%Y-%m-%d_%H-%M-%S`.sql
    - name: Backup Druid Schema
      shell: mysqldump -u root --password={{ password }} --databases {{ db_druid_name}} > {{ mysql_backup_dir }/{{ db_druid_name }}.`date +%Y-%m-%d_%H-%M-%S`.sql
    - name: Backup Ranger Schema
      shell: mysqldump -u root --password={{ password }} --databases {{ db_ranger_name }} > {{ mysql_backup_dir }/{{ db_ranger_name }}.`date +%Y-%m-%d_%H-%M-%S`.sql
    - name: Backup Ranger KMS Schema
      shell: mysqldump -u root --password={{ password }} --databases {{ db_ranger_kms_name }} > {{ mysql_backup_dir }/{{ db_ranger_kms_name }}.`date +%Y-%m-%d_%H-%M-%S`.sql
    - name: Backup Registry Schema
      shell: mysqldump -u root --password={{ password }} --databases {{ db_registry_name }} > {{ mysql_backup_dir }/{{ db_registry_name }}.`date +%Y-%m-%d_%H-%M-%S`.sql
    - name: Backup Superset Schema
      shell: mysqldump -u root --password={{ password }} --databases {{ db_superset_name }} > {{ mysql_backup_dir }/{{ db_superset_name }}.`date +%Y-%m-%d_%H-%M-%S`.sql
