- hosts: hdp
  become: true
  vars:
    yarn_base_log_dir: /var/log/hadoop-yarn/yarn

  tasks:

    - name: Zip Node Manager logs
      archive:
        path: '{{ yarn_base_log_dir }}/hadoop-yarn-nodemanager-{{ ansible_host }}.log'
        dest: '{{ yarn_base_log_dir }}/hadoop-yarn-nodemanager-{{ ansible_host }}.log.gz'
      tags:
        - zip

    - name: Zip Resource Manager logs
      archive:
        path: '{{ yarn_base_log_dir }}/hadoop-yarn-resourcemanager-{{ ansible_host }}.log'
        dest: '{{ yarn_base_log_dir }}/hadoop-yarn-resourcemanager-{{ ansible_host }}.log.gz'
      tags:
        - zip

    - name: Fetch Zipped NM logs
      fetch:
        src: '{{ yarn_base_log_dir }}/hadoop-yarn-nodemanager-{{ ansible_host }}.log.gz'
        dest: /tmp/YARN
        fail_on_missing: no

    - name: Fetch Zipped RM logs
      fetch:
        src: '{{ yarn_base_log_dir }}/hadoop-yarn-resourcemanager-{{ ansible_host }}.log.gz'
        dest: /tmp/YARN
        fail_on_missing: no

    - name: Clean up files
      file:
        path: '{{ yarn_base_log_dir }}/hadoop-yarn-nodemanager-{{ ansible_host }}.log.gz'
        state: absent
      tags:
        - clean

    - name: Clean up files
      file:
        path: '{{ yarn_base_log_dir }}/hadoop-yarn-resourcemanager-{{ ansible_host }}.log.gz'
        state: absent
      tags:
        - clean
