- hosts: os
  become: true
  
  tasks:
    - name: Retrieve remove script from gisthub
      get_url:
        url:            https://gist.githubusercontent.com/dstreev/baec49347e2805a1aff256ba46f63a78/raw/fdaa4110970765daefa8cf46105e65d9e866fb7e/remove-hdp.sh
        dest:           "/tmp/remove_hdp.sh"
        force:          yes
        owner: root
        mode: 0700
        validate_certs: false
    - name: Remove HDP Version {{ hdp_version }}
      shell: /tmp/remove_hdp.sh {{ hdp_version }}
