# Requires a Local Repo for HDP, Ambari and HDP-UTILS
# Repo dirs need to match hdp repo layout.

# MOVED THE IMAGE
#- import_playbook:  ../setup/openjdk_install.yaml

- hosts:             '{{ target_hosts }}'
  become:            true
  tasks:
    - name:          Stop Ambari Agents
      shell:         ambari-agent stop
      ignore_errors: yes
      tags:
        - stop

    - name:          Stop Ambari Server
      shell:         ambari-server stop
      ignore_errors: yes
      tags:
        - stop

    - name:          Remove Ambari
      yum:
        name:        '{{ item }}'
        state:       removed
        skip_broken: yes
      loop:
        - ambari-server
        - ambari-metrics-common
        - ambari-logsearch-portal
        - ambari-logsearch-logfeeder
        - ambari-infra-manager
        - ambari-metrics-monitor
        - ambari-metrics-hadoop-sink
        - ambari-metrics-grafana
        - ambari-metrics-collector
        - ambari-infra-solr-client
        - ambari-infra-solr
        - ambari-agent
        - smartsense-hst

    - name:          List Ambari Repos
      find:
        paths:       /etc/yum.repos.d
        patterns:    "ambari*.repo"
      register:      find_repos
      tags:
        - repo
    - name:          Remove Ambari Repos
      file:
        path:        "{{ item['path'] }}"
        state:       absent
      with_items:    "{{ find_repos['files'] }}"
      tags:
        - repo

    - name:  Remove residual Ambari directories
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/ambari-server
        - /etc/ambari-agent
        - /var/lib/ambari-server
        - /var/lib/ambari-agent
        - /var/lib/ambari-metrics-collector
        - /var/lib/ambari-metrics-grafana
        - /var/lib/ambari-metrics-monitor

- hosts: ambari
  become: true

  tasks:
    - name: Remove marker file for schema creation
      file:
        path:  /hadoop/AMBARI_SCHEMA_BUILT
        state: absent
      tags:
        - server

    - name:  Report Manager Database (Create)
      shell: mysql -h {{ db_host }} -u {{ db_user }} --password={{ db_password }} -e "DROP DATABASE IF EXISTS {{ item.db }}";
      with_items:
        - { db: '{{ db_ambari_name }}' }
        - { db: '{{ db_hive_name }}' }
        - { db: '{{ db_oozie_name }}' }
        - { db: '{{ db_ranger_name }}' }
        - { db: '{{ db_ranger_kms_name }}' }
        - { db: '{{ db_druid_name }}' }
        - { db: '{{ db_superset_name }}' }
        - { db: '{{ db_registry_name }}' }
        - { db: '{{ db_streamline_name }}' }
