- hosts: sdlc

  tasks:
    - name: Create Backup Directory
      file:
        path: '{{ mysql_backup_dir }}'
        state: directory

    - name: Backup Ambari Schema
      shell: mysqldump -h {{ db_host }} -u {{ db_user }} --password={{ db_password }} --databases {{ db_ambari_name }} > {{ mysql_backup_dir }}/{{ db_ambari_name }}.{{ ansible_date_time.iso8601 }}.sql

    - name: Backup Hive Schema
      shell: mysqldump -h {{ db_host }} -u {{ db_user }} --password={{ db_password }} --databases {{ db_hive_name }} > {{ mysql_backup_dir }}/{{ db_hive_name }}.{{ ansible_date_time.iso8601 }}.sql

    - name: Backup Oozie Schema
      shell: mysqldump -h {{ db_host }} -u {{ db_user }} --password={{ db_password }} --databases {{ db_oozie_name }} > {{ mysql_backup_dir }}/{{ db_oozie_name }}.{{ ansible_date_time.iso8601 }}.sql

    - name: Backup Druid Schema
      shell: mysqldump -h {{ db_host }} -u {{ db_user }} --password={{ db_password }} --databases {{ db_druid_name }} > {{ mysql_backup_dir }}/{{ db_druid_name }}.{{ ansible_date_time.iso8601 }}.sql

    - name: Backup Ranger Schema
      shell: mysqldump -h {{ db_host }} -u {{ db_user }} --password={{ db_password }} --databases {{ db_ranger_name }} > {{ mysql_backup_dir }}/{{ db_ranger_name }}.{{ ansible_date_time.iso8601 }}.sql

    - name: Backup Ranger KMS Schema
      shell: mysqldump -h {{ db_host }} -u {{ db_user }} --password={{ db_password }} --databases {{ db_ranger_kms_name }} > {{ mysql_backup_dir }}/{{ db_ranger_kms_name }}.{{ ansible_date_time.iso8601 }}.sql

    - name: Backup Registry Schema
      shell: mysqldump -h {{ db_host }} -u {{ db_user }} --password={{ db_password }} --databases {{ db_registry_name }} > {{ mysql_backup_dir }}/{{ db_registry_name }}.{{ ansible_date_time.iso8601 }}.sql

    - name: Backup Superset Schema
      shell: mysqldump -h {{ db_host }} -u {{ db_user }} --password={{ db_password }} --databases {{ db_superset_name }} > {{ mysql_backup_dir }}/{{ db_superset_name }}.{{ ansible_date_time.iso8601 }}.sql
