- hosts: ambari
  become: true
  tasks:
    - name: Stop Ambari-Server
      shell: ambari-server stop
      tags:
        - server

- hosts: hdp
  become: true
  tasks:
    - name: Stop Ambari Agents
      shell: ambari-agent stop
      tags:
        - agent
