- hosts:                  ambari

  tasks:

    # Set the Repos for the target stack and OS to our Local Repo Location.
    # Vars:               Stack, StackVersion, OSType, RepoId HDP Repo Location,
    #       HDP GPL Repo Location, HDP Utils Repo LOCATION,
    #       Ambari Username and Password
    - name:               Delete Blueprint
      uri:
        url:              '{{ ambari_url_base }}/api/v1/blueprints/DK_FULL'
        method:           DELETE
        user:             '{{ ambari_admin_user }}'
        password:         '{{ ambari_admin_password }}'
        force_basic_auth: yes
        status_code:      200,201
        headers:
          Content-Type:   "text/plain"
          # X-XSRF-HEADER: "valid"
          X-Requested-By: "HDP Ansible BP"
          User-Agent:     "Ansible HDP Best Practices"
      tags:
        - blueprint
    - name:               Register Blueprint
      uri:
        url:              '{{ ambari_url_base }}/api/v1/blueprints/DK_FULL?validate_topology=false'
        body_format:      json
        body:             "{{ lookup('file','../../environment/blueprints/DK_full_bp.json') }}"
        method:           POST
        user:             '{{ ambari_admin_user }}'
        password:         '{{ ambari_admin_password }}'
        force_basic_auth: yes
        status_code:      200,201
        headers:
          Content-Type:   "text/plain"
          # X-XSRF-HEADER: "valid"
          X-Requested-By: "HDP Ansible BP"
          User-Agent:     "Ansible HDP Best Practices"
      tags:
        - blueprint
    # - name: Copy Version Definition File to Ambari
    #   copy:
    #     src:           {{ vdf_file }}
    #     dest:          /tmp/ambari_vdf.json
    #     owner:         root
    #     group:         root
    #     mode:          0644
    #     backup:        yes
    - name: Register Version Definition File
      uri:
        url:              '{{ ambari_url_base }}/api/v1/version_definitions'
        body_format:    json
        body:             "{{ lookup('file','{{ vdf_file }}') }}"
        method:           POST
        user:             '{{ ambari_admin_user }}'
        password:         '{{ ambari_admin_password }}'
        force_basic_auth: yes
        status_code:      200,201,202
        headers:
          Content-Type:   "text/xml"
          # X-XSRF-HEADER: "valid"
          X-Requested-By: "HDP Ansible BP"
          User-Agent:     "Ansible HDP Best Practices"
      tags:
        - vdf
    - name:               Create Cluster
      uri:
        url:              '{{ ambari_url_base }}/api/v1/clusters/{{ cluster_name }}'
        body_format:    json
        body:             "{{ lookup('file','../../environment/blueprints/DK_14_template.json') }}"
        method:           POST
        user:             '{{ ambari_admin_user }}'
        password:         '{{ ambari_admin_password }}'
        force_basic_auth: yes
        status_code:      200,201,202
        headers:
          Content-Type:   "text/plain"
          # X-XSRF-HEADER: "valid"
          X-Requested-By: "HDP Ansible BP"
          User-Agent:     "Ansible HDP Best Practices"
      tags:
        - create
