- hosts: ambari
  tasks:
    - name: Add MariaDB repo
      yum_repository:
        name: MariaDB
        baseurl: http://yum.mariadb.org/10.1/centos7-amd64
        gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
        gpgcheck: 1
        state: present

    - name: Install MariaDB Client
      yum:
        name: MariaDB-client
        state: latest
