- hosts: ambari
  become: true
  tasks:
    - name: Start Ambari-Server
      shell: ambari-server start
  tags:
    - server
- hosts: ambari_agent
  become: true
  tasks:
    - name: Start Ambari Agents
      shell: ambari-agent start
  tags:
    - agent
