- hosts:                  ambari
  vars:
    stack: "HDP"
    stack_version: "3.0"
    os_type: "redhat7"
    hdp_repo_id: "HDP-3.0"
    hdp_utils_repo_id: "HDP-UTILS-1.1.0.22"
    hdp_gpl_repo_id: "HDP-3.0-GPL"

  tasks:

    # Set the Repos for the target stack and OS to our Local Repo Location.
    # Vars:               Stack, StackVersion, OSType, RepoId HDP Repo Location,
    #       HDP GPL Repo Location, HDP Utils Repo LOCATION,
    #       Ambari Username and Password
    - name:               Adjust Ambari Base Repos
      uri:
        url:              '{{ ambari_url_base }}/api/v1/stacks/{{ stack }}/versions/{{ stack_version }}/operating_systems/{{ os_type }}/repositories/{{ hdp_repo_id }}'
        # body_format:      json
        body:
          '{
            "Repositories" : {
              "base_url" : "http://repo.hwx/repo/HDP/centos7/3.x/updates/3.0.0.0",
              "components" : null,
              "default_base_url" : "http://repo.hwx/repo/HDP/centos7/3.x/updates/3.0.0.0",
              "distribution" : null,
              "mirrors_list" : null,
              "os_type" : "redhat7",
              "repo_id" : "HDP-3.0",
              "repo_name" : "HDP",
              "stack_name" : "HDP",
              "stack_version" : "3.0",
              "tags" : [ ],
              "unique" : false
            }
          }'
        method:           PUT
        user:             '{{ ambari_admin_user }}'
        password:         '{{ ambari_admin_password }}'
        force_basic_auth: yes
        status_code:      200,201
        headers:
          Content-Type:   "text/plain"
          # X-XSRF-HEADER: "valid"
          X-Requested-By: "HDP Ansible BP"
          User-Agent:     "Ansible HDP Best Practices"
