# Requires a Local Repo for HDP, Ambari and HDP-UTILS
# Repo dirs need to match hdp repo layout.

# MOVED THE IMAGE
#- import_playbook:    ../setup/openjdk_install.yaml

- hosts:               ambari,ambari_agent
  become:              true
  tasks:
    - name:            Uninstall the Ambari Repo
      yum_repository:
        name:          ambari
        description:   Install the Ambari Repo from our Local Repo Server.
        state:         absent
        baseurl:       '{{ ambari_repo }}'
        #baseurl:      http://{{ repo_server_url }}/repo/ambari/{{ os_version }}/{{ ambari_major_version }}.x/updates/{{ ambari_version }}
        repo_gpgcheck: no
        gpgcheck:      no
      tags:
        - agent
        - server
    - name:            Install the Ambari Repo
      yum_repository:
        name:          ambari
        description:   Install the Ambari Repo from our Local Repo Server.
        state:         present
        baseurl:       '{{ ambari_repo }}'
        #baseurl:      http://{{ repo_server }}/repo/ambari/{{ os_version }}/{{ ambari_major_version }}.x/updates/{{ ambari_version }}
        repo_gpgcheck: no
        gpgcheck:      no
      tags:
        - agent
        - server

- hosts:               ambari
  become:              true
  tasks:
    - name:            Install Ambari Server
      yum:
        name:          ambari-server
        state:         latest
      tags:
        - server

# Required to run db client to init the Database
- import_playbook:     ../../environment/db/mariadb_client.yaml

# Create DB Instance
- import_playbook:     ambari_mariadb_setup.yaml

# Install JDBC Drivers
- import_playbook:     ../../environment/db/jdbc_setup.yaml

- hosts:               ambari_agent
  become:              true
  tasks:
    - name:            Install Ambari Agents
      yum:
        name:          ambari-agent
        state:         latest
      tags:
        - agent

- import_playbook:     fix_agent_ssl.yaml

# Configuration and Start Agents for Manual Registration
- hosts:               ambari_agent
  become:              true
  tasks:
    - name:            Stop Ambari Agents
      shell:           ambari-agent stop
      tags:
        - agent
    - name:            Reset Ambari Agents
      shell:           ambari-agent reset {{ ambari_server }}
      tags:
        - agent

- import_playbook:     ambari_configure.yaml

- import_playbook:     ambari_start.yaml

# - import_playbook:   ambari_blueprint_install.yaml
