# Requires a Local Repo for HDP, Ambari and HDP-UTILS
# Repo dirs need to match hdp repo layout.
- import_playbook:     ../setup/openjdk_install.yaml

- hosts:               hdp
  become:              true
  tasks:
    - name:            Install the Ambari Repo
      yum_repository:
        name:          ambari
        description:   Install the Ambari Repo from our Local Repo Server.
        state:         present
        baseurl:       http://{{ repo_server }}/repo/ambari/{{ os_version }}/{{ ambari_major_version }}.x/updates/{{ ambari_version }}
        repo_gpgcheck: no
        gpgcheck:      no

- hosts:               ambari
  become:              true
  tasks:
    - name:            Install Ambari Server
      yum:
        name:          ambari-server
        state:         latest

# Required to run db client to init the Database
- import_playbook:     ambari_mysql_client.yaml

# Create DB Instance
- import_playbook:     ambari_mysql_setup.yaml

# Install JDBC Drivers
- import_playbook:     jdbc_setup.yaml

- hosts:               hdp
  tasks:
    - name:            Install Ambari Agents
      yum:
        name:          ambari-agent
        state:         latest

- import_playbook:     fix_agent_ssl.yaml

# Configuration and Start Agents for Manual Registration
- hosts:               hdp
  tasks:
    - name:            Reset Ambari Agents
      shell:           ambari-agent reset {{ ambari_server }}

- import_playbook:     ambari_configure.yaml

- hosts: ambari
  become: true
  tasks:
    - name: Start Ambari-Server
      shell: ambari-server start

- hosts: hdp
  become: true
  tasks:
    - name: Start Ambari Agents
      shell: ambari-agent start
