- hosts:         hdp
  tasks:
    - name:      Download the latest Ambari repo
      get_url:
        url:     "{{ hortonworks_repo_base_url }}{{ ambari_path }}{{ ambari_version }}/ambari.repo"
        dest:    /etc/yum.repos.d/
        backup:  yes
        force:   yes
    - name:      Fix URL Paths in repo.
      replace:
        path:    /etc/yum.repos.d/ambari.repo
        regexp:  '(baseurl=){{ hortonworks_repo_base_url }}(.*)?$'
        replace: '\1{{ local_repo_base_url }}\2'
        backup:  yes
    - name:      Stop Ambari Agents
      shell:     ambari-agent stop
    - name:      Upgrade Ambari Agents
      yum:
        name:    ambari-agent
        state:   latest

# Install/Update JDBC Drivers
- import_playbook: jdbc_setup.yaml

- hosts:         ambari
  tasks:
    - name:      Stop Ambari Server
      shell:     ambari-server stop
    - name:      Upgrade Ambari
      yum:
        name:    ambari-server
        state:   latest
    - name:      Upgrade Ambari Server
      shell:     ambari-server upgrade -s
    - name:      Start Ambari Server
      shell:     ambari-server start

# Post Upgrade Steps
- import_playbook: ambari_post_upgrade.yaml

# Fix SSL Agents issues
- import_playbook: fix_agent_ssl.yaml

# Configuration and Start Agents for Manual Registration
- hosts:         hdp
  tasks:
    - name:      Reset Ambari Agents
      shell:     ambari-agent reset {{ ambari_server_host }}
    - name:      Start Ambari Agents
      shell:     ambari-agent start
