- hosts:               hdp
  become:              true
  tasks:

    - name:            Uninstall the Ambari Repo
      yum_repository:
        name:          ambari
        description:   Install the Ambari Repo from our Local Repo Server.
        state:         absent
        baseurl:       '{{ ambari_repo }}'
        #baseurl:      http://{{ repo_server }}/repo/ambari/{{ os_version }}/{{ ambari_major_version }}.x/updates/{{ ambari_version }}
        repo_gpgcheck: no
        gpgcheck:      no
      tags:
        - agent
        - server
    - name:            Install the Ambari Repo
      yum_repository:
        name:          ambari
        description:   Install the Ambari Repo from our Local Repo Server.
        state:         present
        baseurl:       '{{ ambari_repo }}'
        #baseurl:      http://{{ repo_server }}/repo/ambari/{{ os_version }}/{{ ambari_major_version }}.x/updates/{{ ambari_version }}
        repo_gpgcheck: no
        gpgcheck:      no
      tags:
        - agent
        - server

    - name:            Stop Ambari Agents
      shell:           ambari-agent stop

    - name:            Upgrade Ambari Agents
      yum:
        name:          ambari-agent
        state:         latest

# Install/Update JDBC Drivers
- import_playbook:     jdbc_setup.yaml

- hosts:               ambari
  become:              true
  tasks:
    - name:            Stop Ambari Server
      shell:           ambari-server stop
    - name:            Upgrade Ambari
      yum:
        name:          ambari-server
        state:         latest
    - name:            Upgrade Ambari Server
      shell:           ambari-server upgrade -s

# Rerun Ambari Configurations
#- import_playbook:     ambari_configure.yaml

# Post Upgrade Steps  (only to be done AFTER HDP Upgrade)
#- import_playbook:     ambari_post_upgrade.yaml

# Fix SSL Agents issues
#- import_playbook:    fix_agent_ssl.yaml

# Configuration and Start Agents for Manual Registration
- hosts:               hdp
  become:              true
  tasks:
    - name:            Reset Ambari Agents
      shell:           ambari-agent reset {{ ambari_server }}
    - name:            Start Ambari Agents
      shell:           ambari-agent start

- hosts:               ambari
  become:              true
  tasks:
    - name:            Start Ambari Server
      shell:           ambari-server start
