# Requires a Local Repo for HDP, Ambari and HDP-UTILS
# Repo dirs need to match hdp repo layout.

# MOVED THE IMAGE
#- import_playbook:  ../setup/openjdk_install.yaml

- hosts:             os
  become:            true
  vars:
    # Use '_''s as delimiter to match the 'yum' version details
    version: '2_6_5_0_292'
    # This is the /usr/hdp/<directory>
    version_dir: '2.6.5.0-292'

  tasks:
    - name: Remove HDP Packages
      yum:
        name: '{{ item }}'
        state: removed
      loop:
        - accumulo_{{ version }}
        - atlas-metadata_{{ version }}
        - atlas-metadata_{{ version }}-falcon-plugin
        - atlas-metadata_{{ version }}-hive-plugin
        - atlas-metadata_{{ version }}-sqoop-plugin
        - atlas-metadata_{{ version }}-storm-plugin
        - datafu_{{ version }}
        - druid_{{ version }}
        - falcon_{{ version }}
        - flume_{{ version }}
        - hadoop_{{ version }}
        - hadoop_{{ version }}-client
        - hadoop_{{ version }}-hdfs
        - hadoop_{{ version }}-libhdfs
        - hadoop_{{ version }}-mapreduce
        - hadoop_{{ version }}-yarn
        - hbase_{{ version }}
        - hive2_{{ version }}
        - hive2_{{ version }}-jdbc
        - hive_{{ version }}
        - hive_{{ version }}-hcatalog
        - hive_{{ version }}-jdbc
        - hive_{{ version }}-webhcat
        - kafka_{{ version }}
        - knox_{{ version }}
        - livy2_{{ version }}
        - livy_{{ version }}
        - mahout_{{ version }}
        - oozie_{{ version }}
        - oozie_{{ version }}-common
        - oozie_{{ version }}-sharelib
        - oozie_{{ version }}-sharelib-distcp
        - oozie_{{ version }}-sharelib-hcatalog
        - oozie_{{ version }}-sharelib-hive
        - oozie_{{ version }}-sharelib-hive2
        - oozie_{{ version }}-sharelib-mapreduce-streaming
        - oozie_{{ version }}-sharelib-pig
        - oozie_{{ version }}-sharelib-spark
        - oozie_{{ version }}-sharelib-sqoop
        - oozie_{{ version }}-webapp
        - phoenix_{{ version }}
        - pig_{{ version }}
        - ranger_{{ version }}-atlas-plugin
        - ranger_{{ version }}-hbase-plugin
        - ranger_{{ version }}-hdfs-plugin
        - ranger_{{ version }}-hive-plugin
        - ranger_{{ version }}-kafka-plugin
        - ranger_{{ version }}-knox-plugin
        - ranger_{{ version }}-storm-plugin
        - ranger_{{ version }}-yarn-plugin
        - shc_{{ version }}
        - slider_{{ version }}
        - spark2_{{ version }}
        - spark2_{{ version }}-python
        - spark2_{{ version }}-yarn-shuffle
        - spark_{{ version }}
        - spark_{{ version }}-python
        - spark_{{ version }}-yarn-shuffle
        - spark_llap_{{ version }}
        - sqoop_{{ version }}
        - storm_{{ version }}
        - storm_{{ version }}-slider-client
        - superset_{{ version }}
        - tez_{{ version }}
        - tez_hive2_{{ version }}
        - zeppelin_{{ version }}
        - zookeeper_{{ version }}
        - zookeeper_{{ version }}-server
        - hdp-select
      tags:
        - yum

    # The Oozie Client has issues being removed without first deleting the /etc/oozie directory
    - name: Remove Oozie Conf Dir
      file:
        path: /etc/oozie
        state: absent
      tags:
        - oozie
    - name: Remove Oozie Client Package
      yum:
        name: oozie_{{ version }}-client
        state: absent
      tags:
        - oozie

    # After the packages have been removed, drop the hdp directory to prevent hdp-select from picking up bad versions.
    - name: Remove HDP Directory
      file:
        path: /usr/hdp/{{ version_dir }}
        state: absent
      tags:
        - dir

    # If you don't reset the current dir (delete it), the installs will create hardlinks to conf directories
    - name: Reset HDP Current
      file:
        path: /usr/hdp/current
        state: absent
      tags:
        - current
