# Initialize a box for HDP.
# Set Swappiness
# Install NTP
# Disable SELINUX
# Disable THP
# Set somaxconn
# And other LLAP specifics
- hosts:         k8s
  become:        true
  tasks:
    - name:      Yum Installs
      yum:
        name:    '{{ item }}'
        state:   latest
      loop:
        - yum-utils
        - unzip
        - wget
        - gettext
        - less
        - net-tools
        - iproute
        - openssl
        - openssh-server
        - openssh-clients
        - passwd
        - ntp
        - lsof
        - ansible
        - nscd
        - bind-utils
        - java-1.8.0-openjdk
        - java-1.8.0-openjdk-devel
        - git
        - chrony
        - which
        - sudo
        - tmux
        - bash-completion

    # - name:      Start nscd
    #   shell:     nscd

    - name:      Set Swappiness
      shell:     sysctl vm.swappiness=1

    - name:      Set somaxconn
      shell:     sysctl -w net.core.somaxconn=16384

    - name:      Disable Firewalls
      systemd:
        name:    firewalld
        enabled: no

    - name:      Stop Firewalls
      systemd:
        name:    firewalld
        state:   stopped

    - name:      Disable SELINUX
      selinux:
        state:   disabled

    # - name:    Disable THP

    # - name:    Set somaxconn
