# Initialize a box for HDP.
# Set Swappiness
# Install NTP
# Disable SELINUX
# Disable THP
# Set somaxconn
# And other LLAP specifics
- hosts:         '{{ all_target }}'
  become:        true
  tasks:
    - name:      Yum Installs
      yum:
        name:    '{{ item }}'
        state:   latest
      loop:
        - yum-utils
        - unzip
        - wget
        - gettext
        - less
        - net-tools
        - iproute
        - openssl
        - openssh-server
        - openssh-clients
        - passwd
        - ntp
        - lsof
        - nscd
        - bind-utils
        - java-1.8.0-openjdk
        - java-1.8.0-openjdk-devel
        - git
        - chrony
        - which
        - sudo
        - tmux
        - bash-completion
      tags:
        - utils

    # - name:      Start nscd
    #   shell:     nscd

    - name:      Set Swappiness
      shell:     sysctl vm.swappiness=1
      tags:
        - env

    - name:
      file:
        path: /etc/sysctl.d/cdp-settings.conf
        state: touch
        owner: root
        group: root
        mode: 0744

    - name:      Persist Swappiness
      lineinfile:
        path: /etc/sysctl.d/cdp-settings.conf
        regex: '^vm.swappiness'
        line: vm.swappiness=1
      tags:
        - env

    - name:      Set somaxconn
      shell:     sysctl -w net.core.somaxconn=16384
      tags:
        - env

    - name:      Persist somaxconn
      lineinfile:
        path: /etc/sysctl.d/cdp-settings.conf
        regex: '^net.core.somaxconn'
        line: net.core.somaxconn=16384
      tags:
        - env

    - name:      Disable Firewalls
      systemd:
        name:    firewalld
        enabled: no
      tags:
        - env

    - name:      Stop Firewalls
      systemd:
        name:    firewalld
        state:   stopped
      tags:
        - env

    - name:      Disable SELINUX
      selinux:
        state:   disabled
      tags:
        - env

    - name: Disable THP DeFrag
      shell: echo never > /sys/kernel/mm/transparent_hugepage/defrag
      tags:
        - env

    - name: Disable THP
      shell: echo never > /sys/kernel/mm/transparent_hugepage/enabled
      tags:
        - env

    # Will keep activating THP, so disable it.
    - name: Turn off tuned
      service:
        name: tuned
        state: stopped
        enabled: no

    - name: Persist THP Defrag Disabled
      lineinfile:
        path: /etc/rc.local
        regex: '\/sys\/kernel\/mm\/transparent_hugepage\/defrag'
        line: echo never > /sys/kernel/mm/transparent_hugepage/defrag
      tags:
        - env

    - name: Persist THP Disabled
      lineinfile:
        path: /etc/rc.local
        regex: '\/sys\/kernel\/mm\/transparent_hugepage\/enabled'
        line: echo never > /sys/kernel/mm/transparent_hugepage/enabled
      tags:
        - env

    # - name:    Disable THP

    # - name:    Set somaxconn
