- hosts:         all
  become:        true

  tasks:
    - name:      Create Hadoop Data Directories
      file:
        path:    /cluster_data/{{ cluster_name }}
        state:   directory
        owner:   root
        mode:    755


    - name:      Set Permissions
      file:
        path:    /cluster_data
        state:   directory
        recurse: yes
        mode:    755

    - name:      Create Symlink for Hadoop Directories
      file:
        src:     /cluster_data/{{ cluster_name }}
        dest:    /hadoop
        owner:   root
        group:   root
        state:   link
