- hosts: os
  become: true

  tasks:
    - name: Copy out new etc_hosts file
      copy:
        src: ../support/etc_hosts
        dest: /etc/hosts
        owner: root
        group: root
        mode: 0644
