version: '3.6'
services:
  ambari:
    hostname: ambari-${ENV_INSTANCE}.hwx
    image: dstreev/centos7_sshd:${IMAGE_TAG}
    ports:
      - target: 22
        published: 220${ENV_INSTANCE}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hdpdata
        target: /hadoop
      - type: volume
        source: hdplog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hdp_base:
        aliases:
          - ambari-${ENV_INSTANCE}.hwx
    deploy:
      placement:
        constraints:
          - node.labels.hdp.ambari == true

  os02:
    hostname: os2-${ENV_INSTANCE}.hwx
    image: dstreev/centos7_sshd:${IMAGE_TAG}
    ports:
      - target: 22
        published: 220${ENV_INSTANCE}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hdpdata
        target: /hadoop
      - type: volume
        source: hdplog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hdp_base:
        aliases:
          - os02-${ENV_INSTANCE}.hwx
    deploy:
      placement:
        constraints:
          - node.labels.hdp.host == os02
  os03:
    hostname: os3-${ENV_INSTANCE}.hwx
    image: dstreev/centos7_sshd:${IMAGE_TAG}
    ports:
      - target: 22
        published: 220${ENV_INSTANCE}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hdpdata
        target: /hadoop
      - type: volume
        source: hdplog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hdp_base:
        aliases:
          - os03-${ENV_INSTANCE}.hwx
    deploy:
      placement:
        constraints:
          - node.labels.hdp.host == os03
  os04:
    hostname: os04-${ENV_INSTANCE}.hwx
    image: dstreev/centos7_sshd:${IMAGE_TAG}
    ports:
      - target: 22
        published: 220${ENV_INSTANCE}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hdpdata
        target: /hadoop
      - type: volume
        source: hdplog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hdp_base:
        aliases:
          - os04-${ENV_INSTANCE}.hwx
    deploy:
      placement:
        constraints:
          - node.labels.hdp.host == os04
  os10:
    hostname: os10-${ENV_INSTANCE}.hwx
    image: dstreev/centos7_sshd:${IMAGE_TAG}
    ports:
      - target: 22
        published: 220${ENV_INSTANCE}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hdpdata
        target: /hadoop
      - type: volume
        source: hdplog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hdp_base:
        aliases:
          - os10-${ENV_INSTANCE}.hwx
    deploy:
      placement:
        constraints:
          - node.labels.hdp.host == os10
  os11:
    hostname: os11-${ENV_INSTANCE}.hwx
    image: dstreev/centos7_sshd:${IMAGE_TAG}
    ports:
      - target: 22
        published: 220${ENV_INSTANCE}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hdpdata
        target: /hadoop
      - type: volume
        source: hdplog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hdp_base:
        aliases:
          - os11-${ENV_INSTANCE}.hwx
    deploy:
      placement:
        constraints:
          - node.labels.hdp.host == os11
  os12:
    hostname: os12-${ENV_INSTANCE}.hwx
    image: dstreev/centos7_sshd:${IMAGE_TAG}
    ports:
      - target: 22
        published: 220${ENV_INSTANCE}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hdpdata
        target: /hadoop
      - type: volume
        source: hdplog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hdp_base:
        aliases:
          - os12-${ENV_INSTANCE}.hwx
    deploy:
      placement:
        constraints:
          - node.labels.hdp.host == os12
  os13:
    hostname: os13-${ENV_INSTANCE}.hwx
    image: dstreev/centos7_sshd:${IMAGE_TAG}
    ports:
      - target: 22
        published: 220${ENV_INSTANCE}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hdpdata
        target: /hadoop
      - type: volume
        source: hdplog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hdp_base:
        aliases:
          - os13-${ENV_INSTANCE}.hwx
    deploy:
      placement:
        constraints:
          - node.labels.hdp.host == os13

networks:
  hdp_base:
    external: true
    driver: overlay
    attachable: true
volumes:
  hdpdata:
    driver: local
  hdpdata:
    driver: local
  hdplog:
    driver: local
