version: '3.6'
services:
  db:
    hostname: db.hwx
    image: mariadb:10.2
    ports:
      - 33060:3306
    volumes:
      - type: volume
        source: mariadb
        target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: hortonworks
      MYSQL_USER: ambari
      MYSQL_PASSWORD: hortonworks
    networks:
      hdp_base:
        aliases:
          - db.hwx
    deploy:
      placement:
        constraints:
          - node.labels.hdp.db == true
  repo:
    hostname: repo.hwx
    image: dstreev/hdp-repo:latest
    ports:
      - 38000:80
    volumes:
      - type: bind
        source: /var/www/html
        target: /www
    networks:
      hdp_base:
        aliases:
          - repo.hwx
    deploy:
      placement:
        constraints:
          - node.labels.hdp.repo == true

networks:
  hdp_base:
    external: true
    driver: overlay
    attachable: true
volumes:
  mariadb:
    driver: local
