version: '3.6'
services:
  db:
    hostname: db-${ENV_INSTANCE}.hwx
    image: mariadb:10.2
    ports:
      - 336${ENV_INSTANCE}:3306
    volumes:
      - type: volume
        source: mariadb
        target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: hortonworks
      MYSQL_USER: ambari
      MYSQL_PASSWORD: hortonworks
    networks:
      hdp_base:
        aliases:
          - db-${ENV_INSTANCE}.hwx
    deploy:
      placement:
        constraints:
          - node.labels.hdp.db == true
  repo:
    hostname: repo-${ENV_INSTANCE}.hwx
    image: dstreev/hdp-repo:latest
    ports:
      - 380${ENV_INSTANCE}:80
    volumes:
      - type: bind
        source: /var/www/html
        target: /www
    networks:
      hdp_base:
        aliases:
          - repo-${ENV_INSTANCE}.hwx
    deploy:
      placement:
        constraints:
          - node.labels.hdp.repo == true
  ambari:
    hostname: ambari-${ENV_INSTANCE}.hwx
    image: dstreev/centos7_sshd:${IMAGE_TAG}
    ports:
      - target: 22
        published: 220${ENV_INSTANCE}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hdpdata
        target: /hadoop
      - type: volume
        source: hdplog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hdp_base:
        aliases:
          - ambari-${ENV_INSTANCE}.hwx
    deploy:
      placement:
        constraints:
          - node.labels.hdp.ambari == true

  os02:
    hostname: os2-${ENV_INSTANCE}.hwx
    image: dstreev/centos7_sshd:${IMAGE_TAG}
    ports:
      - target: 22
        published: 220${ENV_INSTANCE}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hdpdata
        target: /hadoop
      - type: volume
        source: hdplog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hdp_base:
        aliases:
          - os02-${ENV_INSTANCE}.hwx
    deploy:
      placement:
        constraints:
          - node.labels.hdp.host == os02
  os03:
    hostname: os3-${ENV_INSTANCE}.hwx
    image: dstreev/centos7_sshd:${IMAGE_TAG}
    ports:
      - target: 22
        published: 220${ENV_INSTANCE}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hdpdata
        target: /hadoop
      - type: volume
        source: hdplog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hdp_base:
        aliases:
          - os03-${ENV_INSTANCE}.hwx
    deploy:
      placement:
        constraints:
          - node.labels.hdp.host == os03
  os04:
    hostname: os04-${ENV_INSTANCE}.hwx
    image: dstreev/centos7_sshd:${IMAGE_TAG}
    ports:
      - target: 22
        published: 220${ENV_INSTANCE}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hdpdata
        target: /hadoop
      - type: volume
        source: hdplog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hdp_base:
        aliases:
          - os04-${ENV_INSTANCE}.hwx
    deploy:
      placement:
        constraints:
          - node.labels.hdp.host == os04
  os05:
    hostname: os05-${ENV_INSTANCE}.hwx
    image: dstreev/centos7_sshd:${IMAGE_TAG}
    ports:
      - target: 22
        published: 220${ENV_INSTANCE}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hdpdata
        target: /hadoop
      - type: volume
        source: hdplog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hdp_base:
        aliases:
          - os05-${ENV_INSTANCE}.hwx
    deploy:
      placement:
        constraints:
          - node.labels.hdp.host == os05
  os06:
    hostname: os06-${ENV_INSTANCE}.hwx
    image: dstreev/centos7_sshd:${IMAGE_TAG}
    ports:
      - target: 22
        published: 220${ENV_INSTANCE}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hdpdata
        target: /hadoop
      - type: volume
        source: hdplog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hdp_base:
        aliases:
          - os06-${ENV_INSTANCE}.hwx
    deploy:
      placement:
        constraints:
          - node.labels.hdp.host == os06
  os07:
    hostname: os07-${ENV_INSTANCE}.hwx
    image: dstreev/centos7_sshd:${IMAGE_TAG}
    ports:
      - target: 22
        published: 220${ENV_INSTANCE}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hdpdata
        target: /hadoop
      - type: volume
        source: hdplog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hdp_base:
        aliases:
          - os07-${ENV_INSTANCE}.hwx
    deploy:
      placement:
        constraints:
          - node.labels.hdp.host == os07
  os10:
    hostname: os10-${ENV_INSTANCE}.hwx
    image: dstreev/centos7_sshd:${IMAGE_TAG}
    ports:
      - target: 22
        published: 220${ENV_INSTANCE}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hdpdata
        target: /hadoop
      - type: volume
        source: hdplog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hdp_base:
        aliases:
          - os10-${ENV_INSTANCE}.hwx
    deploy:
      placement:
        constraints:
          - node.labels.hdp.host == os10
  os11:
    hostname: os11-${ENV_INSTANCE}.hwx
    image: dstreev/centos7_sshd:${IMAGE_TAG}
    ports:
      - target: 22
        published: 220${ENV_INSTANCE}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hdpdata
        target: /hadoop
      - type: volume
        source: hdplog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hdp_base:
        aliases:
          - os11-${ENV_INSTANCE}.hwx
    deploy:
      placement:
        constraints:
          - node.labels.hdp.host == os11
  os12:
    hostname: os12-${ENV_INSTANCE}.hwx
    image: dstreev/centos7_sshd:${IMAGE_TAG}
    ports:
      - target: 22
        published: 220${ENV_INSTANCE}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hdpdata
        target: /hadoop
      - type: volume
        source: hdplog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hdp_base:
        aliases:
          - os12-${ENV_INSTANCE}.hwx
    deploy:
      placement:
        constraints:
          - node.labels.hdp.host == os12
  os13:
    hostname: os13-${ENV_INSTANCE}.hwx
    image: dstreev/centos7_sshd:${IMAGE_TAG}
    ports:
      - target: 22
        published: 220${ENV_INSTANCE}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hdpdata
        target: /hadoop
      - type: volume
        source: hdplog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hdp_base:
        aliases:
          - os13-${ENV_INSTANCE}.hwx
    deploy:
      placement:
        constraints:
          - node.labels.hdp.host == os13
  os14:
    hostname: os14-${ENV_INSTANCE}.hwx
    image: dstreev/centos7_sshd:${IMAGE_TAG}
    ports:
      - target: 22
        published: 220${ENV_INSTANCE}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hdpdata
        target: /hadoop
      - type: volume
        source: hdplog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hdp_base:
        aliases:
          - os14-${ENV_INSTANCE}.hwx
    deploy:
      placement:
        constraints:
          - node.labels.hdp.host == os14
  os15:
    hostname: os15-${ENV_INSTANCE}.hwx
    image: dstreev/centos7_sshd:${IMAGE_TAG}
    ports:
      - target: 22
        published: 220${ENV_INSTANCE}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hdpdata
        target: /hadoop
      - type: volume
        source: hdplog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hdp_base:
        aliases:
          - os15-${ENV_INSTANCE}.hwx
    deploy:
      placement:
        constraints:
          - node.labels.hdp.host == os15
  os16:
    hostname: os16-${ENV_INSTANCE}.hwx
    image: dstreev/centos7_sshd:${IMAGE_TAG}
    ports:
      - target: 22
        published: 220${ENV_INSTANCE}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hdpdata
        target: /hadoop
      - type: volume
        source: hdplog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hdp_base:
        aliases:
          - os16-${ENV_INSTANCE}.hwx
    deploy:
      placement:
        constraints:
          - node.labels.hdp.host == os16
  os17:
    hostname: os17-${ENV_INSTANCE}.hwx
    image: dstreev/centos7_sshd:${IMAGE_TAG}
    ports:
      - target: 22
        published: 220${ENV_INSTANCE}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hdpdata
        target: /hadoop
      - type: volume
        source: hdplog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hdp_base:
        aliases:
          - os17-${ENV_INSTANCE}.hwx
    deploy:
      placement:
        constraints:
          - node.labels.hdp.host == os17
  os18:
    hostname: os18-${ENV_INSTANCE}.hwx
    image: dstreev/centos7_sshd:${IMAGE_TAG}
    ports:
      - target: 22
        published: 220${ENV_INSTANCE}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hdpdata
        target: /hadoop
      - type: volume
        source: hdplog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hdp_base:
        aliases:
          - os18-${ENV_INSTANCE}.hwx
    deploy:
      placement:
        constraints:
          - node.labels.hdp.host == os18
  os19:
    hostname: os19-${ENV_INSTANCE}.hwx
    image: dstreev/centos7_sshd:${IMAGE_TAG}
    ports:
      - target: 22
        published: 220${ENV_INSTANCE}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hdpdata
        target: /hadoop
      - type: volume
        source: hdplog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hdp_base:
        aliases:
          - os19-${ENV_INSTANCE}.hwx
    deploy:
      placement:
        constraints:
          - node.labels.hdp.host == os19

networks:
  hdp_base:
    external: true
    driver: overlay
    ipam:
      config:
        - subnet: 192.168.${ENV_INSTANCE}.0/24
    attachable: true
volumes:
  mariadb:
    driver: local
  hdpdata:
    driver: local
  hdpdata:
    driver: local
  hdplog:
    driver: local
