- hosts: edge
  become: true

  tasks:
    - name: Fetch HadoopCLI Binaries
      get_url:
        url:        '{{ hadoop_cli_bin_link }}'
        dest:       "/tmp/hadoopcli.{{ hadoop_cli_version }}.tar.gz"
        force:      yes
    - name: Remove Old References
      file:
        path: "/tmp/hadoop-cli-{{ hadoop_cli_version }}"
        state: absent
    - name:         Unpack HadoopCLI Binaries
      unarchive:
        src:        "/tmp/hadoopcli.{{ hadoop_cli_version }}.tar.gz"
        dest:       "/tmp"
        remote_src: yes
    - name:         Install HadoopCLI
      shell: /tmp/hadoop-cli-{{ hadoop_cli_version }}/setup.sh
