- hosts:               hdp
  become:              true
  vars:
    hwc_version: 1.0.0
    hdp_version: 3.1.0.41-5

  tasks:

    - name:            Install / Upgrade HWC Libraries
      yum:
        name:          hive_warehouse_connector
        state:         latest


    - name:   Establish General Symlinks for HWC Libs
      file:
        src: /usr/hdp/{{ hdp_version }}/hive_warehouse_connector/{{ item.base }}-{{ hwc_version }}.{{ hdp_version}}.{{ item.ext }}
        dest: /usr/hdp/{{ hdp_version }}/hive_warehouse_connector/{{ item.base }}.{{ item.ext }}
        state: link
      with_items:
        - { base: 'pyspark_hwc', ext: 'zip' }
        - { base: 'hive-warehouse-connector-assembly', ext: 'jar' }

- hosts: ambari
  become: true

  vars:
    ambari_config: /var/lib/ambari-server/resources/scripts/configs.py

  tasks:

# Spark Configurations:
#    spark.sql.hive.hiveserver2.jdbc.url
#    spark.datasource.hive.warehouse.metastoreUri
#    spark.datasource.hive.warehouse.load.staging.dir
#    spark.hadoop.hive.llap.daemon.service.hosts
#    spark.hadoop.hive.zookeeper.quorum

    - name: Configure ...
      shell: