- hosts: hdp
  become: true
  tasks:
    - name: Install OpenJDK
      yum:
        name: java-1.8.0-openjdk
        state: latest
    - name: Install OpenJDK Devel
      yum:
        name: java-1.8.0-openjdk-devel
        state: latest
