# Install JDK
- hosts: hdp

  tasks:
  - name: Install / Verify wget
    yum:
      name: wget
      state: latest

  - name: Download Java RPM
    get_url:
      url: "{{ download_url }}"
      dest: "{{ java_archive }}"
      force: no
      headers: "Cookie:oraclelicense=accept-securebackup-cookie"
      validate_certs: no
    #shell: "wget -q -O {{java_archive}} --no-check-certificate --no-cookies --header 'Cookie: oraclelicense=accept-securebackup-cookie' {{download_url}} creates={{java_archive}}"

  - name: Install JDK
    yum:
      name: "{{ java_archive }}"
      state: present
