# Build and Start the Metastore and Repo
# - import_playbook: ../infrastructure/infra.yaml

- hosts: hdp_{{ env_set }}
  vars:
    docker_network_name: home

  become: true
  tasks:
    - name: Create Device HDP Log directory
      file:
        path: /data_1/docker_{{ env_instance }}/hdp/log
        state: directory
        owner: root
        mode: 0755
    - name: Create Device HDF Log directory
      file:
        path: /data_1/docker_{{ env_instance }}/hdf/log
        state: directory
        owner: root
        mode: 0755
    - name: Create Device HDP directory /data
      file:
        path: /data/docker_{{ env_instance }}/hdp/data
        state: directory
        owner: root
        mode: 0755
    - name: Create Device HDP directory /data_1
      file:
        path: /data_1/docker_{{ env_instance }}/hdp/data
        state: directory
        owner: root
        mode: 0755
    - name: Create Device HDF directory /data
      file:
        path: /data/docker_{{ env_instance }}/hdf/data
        state: directory
        owner: root
        mode: 0755
    - name: Create Device HDF directory /data_1
      file:
        path: /data_1/docker_{{ env_instance }}/hdf/data
        state: directory
        owner: root
        mode: 0755

    - name: Set State of HDP Containers to {{ env_state}}
      docker_container:
        name: hdp-{{ ansible_hostname }}-{{ env_instance }}
        pull: true
        image: dstreev/centos7_sshd:{{ image_tag }}
        ignore_image: yes
        privileged: yes
        hostname: hdp-{{ ansible_hostname }}-{{ env_instance }}.{{ docker_network_name }}
        volumes:
          - "/var/lib/sss/pipes/:/var/lib/sss/pipes/:rw"
          - "/var/lib/sss/mc/:/var/lib/sss/mc/:ro"
          - "/data/docker_{{ env_instance }}/hdp/data:/hadoop"
          - "/data/docker_{{ env_instance }}/hdf/data:/hdf"
          - "/data_1/docker_{{ env_instance }}/hdp/data:/hadoop_1"
          - "/data_1/docker_{{ env_instance }}/hdf/data:/hdf_1"
          - "/data_1/docker_{{ env_instance }}/log:/var/log"
        dns_search_domains:
          - '{{ docker_network_name }}'
        dns_servers:
        restart: yes
        etc_hosts:
          os01.streever.local: 10.0.1.11
          os02.streever.local: 10.0.1.12
          os03.streever.local: 10.0.1.13
          os04.streever.local: 10.0.1.14
          os05.streever.local: 10.0.1.15
          os06.streever.local: 10.0.1.16
          os07.streever.local: 10.0.1.17
          os10.streever.local: 10.0.1.20
          os11.streever.local: 10.0.1.21
          os12.streever.local: 10.0.1.22
          os13.streever.local: 10.0.1.23
          os14.streever.local: 10.0.1.24
          os15.streever.local: 10.0.1.25
          os16.streever.local: 10.0.1.26
          os17.streever.local: 10.0.1.27
          os18.streever.local: 10.0.1.28
          os19.streever.local: 10.0.1.29
        restart_policy: unless-stopped
        network_mode: '{{ docker_network_name }}'
        networks:
          - name : '{{ docker_network_name }}'
            aliases :
              - hdp-{{ ansible_hostname }}-{{ env_instance }}.{{ docker_network_name }}
            # links:
            #   - hdp-{{ ansible_hostname }}-{{ env_instance }}.core
        purge_networks: yes
        state : '{{ env_state }}'
        ports :
          - "220{{ env_instance }}:22"
