####################
# Used to install the basics on a new CentOS7 hosts
####################

- hosts: hdp_base
  tasks:
    - name: yum-utils install
      yum:
        name: yum-utils
        state: latest
    - name: device-mapper install
      yum:
        name: device-mapper-persistent-data
        state: latest
    - name: lvm2 install
      yum:
        name: lvm2
        state: latest
    - name: Docker Repo Install
      yum_repository:
        name: docker-ce-stable
        description: Docker CE Repo
        baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    - name: Docker CE Installation
      yum:
        name: docker-ce
        state: latest
    - name: Docker enable
      systemd:
        name: docker
        enabled: yes
    - name: Start docker
      systemd:
        name: docker
        state: started

    - name: Install Kubernetes Repo
      yum_repository:
        name:          Kubernetes
        description:   Install the Kubernetes Repo
        state:         present
        baseurl:       https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        repo_gpgcheck: yes
        gpgcheck:      yes

    - name: Install Kubernetes GPG Keys
      rpm_key:
        state: present
        key: https://packages.cloud.google.com/yum/doc/yum-key.gpg
    - name: Install Kubernetes GPG Keys
      rpm_key:
        state: present
        key: https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

    - name: Copy out k8s.conf
      copy:
        src: /Users/dstreev/projects/david/hwx-ansible/environment/support/k8s.conf
        dest: /etc/sysctl.d/

    - name: Install kubernetes
      yum:
        name: kubelet
        state: present
    - name: Install Kubernetes
      yum:
        name: kubeadm
        state: present
    - name: Install kubernetes
      yum:
        name: kubectl
        state: present
    - name: Enable Kubernetes
      systemd:
        name: kubelet
        enabled: yes
    - name: Set Kubernetes cgroup to match docker
      replace:
        path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
        regexp: '^(Environment="KUBELET_CGROUP_ARGS=--)cgroup-driver=systemd(")?$'
        replace: '\1cgroup-driver=cgroupfs\2'
        backup: yes
    - name: Start Kubernetes
      systemd:
        name: kubelet
        state: restarted
