# This process will generate several datasets to exhibit an
# incremental load process.  The data will be loaded passthrough
# various methods to show and contrast the efforts.

- hosts: sdlc
  vars:
    mr_data_util_bin: https://github.com/dstreev/iot-data-utility/releases/download/untagged-f3cc6cbacd1ffdb48d29/mr-data-utility-3.0-SNAPSHOT-shaded.jar
  become: true
  # become_user: '{{ user }}'

  tasks:
    - name: Create bin directory
      shell: mkdir -p /home/{{ user }}/datagen
      become: true

    - name: Set home permissions
      shell: chown -R {{ user }}:{{ user }} /home/{{ user }}

    - name: Copy over the library for the data generator
      get_url:
        url: '{{ mr_data_util_bin }}'
        dest: '/home/{{ user }}/datagen/mr-data-utility.jar'

    - name: Copy over the data generator control file
      copy:
        src: ../support/acid-gen1.yaml
        dest: '/home/{{ user }}/datagen/support/acid-gen1.yaml'

    #
    # - name: Copy over the DDL scripts used to build the supporting tables for this exercise.
    #
    # - name: Run the data generator to create source files for this process.
    #
    # - name: Copy over the script used to move the generated files and build the process with the traditional append method.
