# This process will generate several datasets to exhibit an
# incremental load process.  The data will be loaded passthrough
# various methods to show and contrast the efforts.

- hosts: sdlc
  vars:
    mr_data_util_bin: https://github.com/dstreev/iot-data-utility/releases/download/untagged-f3cc6cbacd1ffdb48d29/mr-data-utility-3.0-SNAPSHOT-shaded.jar

  tasks:
    - name: Create bin directory
      debug: home_dir=ansible_env.HOME
      shell: mkdir -p {{ home_dir }}/datagen
      become: true

    - name: Set home permissions
      debug: home_dir=ansible_env.HOME
      shell: chown -R {{ user }}:{{ user }} {{ home_dir }}

    - name: Copy over the library for the data generator
      get_url:
        url: '{{ mr_data_util_bin }}'
        dest: '{{ ansible_env.HOME }}/datagen/mr-data-utility.jar'

    # - name: Copy over the data generator control file
    #
    # - name: Copy over the DDL scripts used to build the supporting tables for this exercise.
    #
    # - name: Run the data generator to create source files for this process.
    #
    # - name: Copy over the script used to move the generated files and build the process with the traditional append method.
