- hosts: agent
  become: true

  tasks:

    # This alone wasn't capturing all configs to stop and disable
    - name: Enable and Start CM Agent
      service:
        name: cloudera-scm-agent
        enabled: yes
        state: started
