# Requires a Local Repo for HDP, Ambari and HDP-UTILS
# Repo dirs need to match hdp repo layout.

# MOVED THE IMAGE
#- import_playbook:    ../setup/openjdk_install.yaml

- hosts:               all
  become:              true
  tasks:
    - name:            Uninstall the Cloudera Manager Repo
      yum_repository:
        name:          cldr
        description:   Install the CM Repo from our Local Repo Server.
        state:         absent
        baseurl:       '{{ manager_repo }}'
        repo_gpgcheck: no
        gpgcheck:      no
      tags:
        - agent
        - server
    - name:            Install the Cloudera Manager Repo
      yum_repository:
        name:          cloudera-manager
        description:   Install the CM Repo from our Local Repo Server.
        state:         present
        baseurl:       '{{ manager_repo }}'
        repo_gpgcheck: no
        gpgcheck:      no
      tags:
        - agent
        - server

- hosts:               manager
  become:              true
  tasks:
    - name:            Install Clouder Manager Server
      yum:
        name:          cloudera-manager-server
        state:         latest
      tags:
        - server
    - name:            Install Clouder Manager Daemons
      yum:
        name:          cloudera-manager-daemons
        state:         latest
      tags:
        - server

    - name:            Install Cloudera Manager Agents
      yum:
        name:          cloudera-manager-agent
        state:         latest
      tags:
        - server

# Required to run db client to init the Database
- import_playbook:     ../../environment/db/mariadb_client.yaml

# Install JDBC Drivers
- import_playbook:     ../../environment/db/jdbc_setup.yaml

# Create DB Instance
- import_playbook:     mariadb_setup.yaml

- hosts:               all
  become:              true
  tasks:
    - name:            Install Clouder Manager Daemons
      yum:
        name:          cloudera-manager-daemons
        state:         latest
      tags:
        - agent

    - name:            Install Cloudera Manager Agents
      yum:
        name:          cloudera-manager-agent
        state:         latest
      tags:
        - agent

# Configuration and Start Agents for Manual Registration
#- hosts:               cldr
#  become:              true
#  tasks:
#    - name:            Stop CM Agents
#      shell:           cloudera-manager-agent stop
#      tags:
#        - agent
#    - name:            Reset Ambari Agents
#      shell:           ambari-agent reset {{ ambari_server }}
#      tags:
#        - agent

#- import_playbook:     ambari_configure.yaml

#- import_playbook:     ambari_start.yaml

# - import_playbook:   ambari_blueprint_install.yaml
