
- import_playbook: cm_repo.yaml

- hosts:               manager
  become:              true
  tasks:
    - name:            Install Clouder Manager Server
      yum:
        name:          cloudera-manager-server
        state:         latest
      tags:
        - server
    - name:            Install Clouder Manager Daemons
      yum:
        name:          cloudera-manager-daemons
        state:         latest
      tags:
        - server

    - name:            Install Cloudera Manager Agents
      yum:
        name:          cloudera-manager-agent
        state:         latest
      tags:
        - server

# Required to run db client to init the Database
- import_playbook:     ../../environment/db/mariadb_client.yaml

# Install JDBC Drivers
- import_playbook:     ../../environment/db/jdbc_setup.yaml

# Create DB Instance
- import_playbook:     db_setup.yaml

- import_playbook:     cm_start.yaml


