- hosts:     manager
  become:    true
  tasks:
#    - name:  Create CM database
#      shell: mysql -h {{ db_host }} -u {{ db_user }} -p{{ db_password }} -e "create database if not exists {{ db_cm_name }} DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci"
#      tags:
#        - server
#    - name:  Create Hive database
#      shell: mysql -h {{ db_host }} -u {{ db_user }} -p{{ db_password }} -e "create database if not exists {{ db_hive_name }}"
#      tags:
#        - server
#    - name:  Create Oozie database
#      shell: mysql -h {{ db_host }} -u {{ db_user }} -p{{ db_password }} -e "create database if not exists {{ db_oozie_name }}"
#      tags:
#        - server
#    - name:  Create Ranger database
#      shell: mysql -h {{ db_host }} -u {{ db_user }} -p{{ db_password }} -e "create database if not exists {{ db_ranger_name }}"
#      tags:
#        - server
#    - name:  Create Ranger KMS database
#      shell: mysql -h {{ db_host }} -u {{ db_user }} -p{{ db_password }} -e "create database if not exists {{ db_ranger_kms_name }}"
#      tags:
#        - server

    # Druid DB must be created with UTF-8!!
#    - name:  Create Druid
#      shell: mysql -h {{ db_host }} -u {{ db_user }} -p{{ db_password }} -e "create database if not exists {{ db_druid_name }} DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci"
#      tags:
#        - server
#    - name:  Create Superset
#      shell: mysql -h {{ db_host }} -u {{ db_user }} -p{{ db_password }} -e "create database if not exists {{ db_superset_name }}"
#      tags:
#        - server
#    - name:  Create Registry
#      shell: mysql -h {{ db_host }} -u {{ db_user }} -p{{ db_password }} -e "create database if not exists {{ db_registry_name }}"
#      tags:
#        - server
#    - name:  Create Streamline database
#      shell: mysql -h {{ db_host }} -u {{ db_user }} -p{{ db_password }} -e "create database if not exists {{ db_streamline_name }}"
#      tags:
#        - server

    - name:  Build CM Schema
      shell: /opt/cloudera/cm/schema/scm_prepare_database.sh -h {{ db_host }} -u {{ db_user }} -p{{ db_password }} {{ db_type }} {{ db_cm_name }} {{ db_user }} {{ db_password }}
#      mysql -h {{ db_host }} -u {{ db_user }} -p{{ db_password }} -D {{ db_ambari_name }} < /var/lib/ambari-server/resources/Ambari-DDL-MySQL-CREATE.sql
      # When this file exists, the process will NOT run.
      args:
        creates: /hadoop/CM_SCHEMA_BUILT
      tags:
        - db
    - name: Create Schema Created Marker File
      file:
        path: /hadoop/CM_SCHEMA_BUILT
        owner: root
        mode: 0644
        state: touch
      tags:
        - db
