- hosts: monitor
  become: true
  tasks:

  - name:
    shell: docker volume create portainer_data
  - name:
    # docker run -d -p 9000:9000 -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer
    docker_container:
      name: portainer
      pull: true
      image: portainer/portainer
      privileged: yes
      hostname: portainer
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        - "/data/portainer_data:/data"
      restart: yes
      restart_policy: unless-stopped
      state : started
      ports :
        - "9000:9000"



  # - name: Portainer Global Agent
  #   shell:  docker service create --name portainer_agent --network home -e AGENT_CLUSTER_ADDR=tasks.portainer_agent --mode global --mount type=bind,src=//var/run/docker.sock,dst=/var/run/docker.sock portainer/agent

  # - name: Portainer
  #   shell: docker service create --name portainer --network home --publish 9000:9000 --replicas=1 --constraint 'node.role == manager' portainer/portainer -H "tcp://tasks.portainer_agent:9001"
