- hosts: hdp
  vars:

  tasks:
    - name: ping cluster peers (Full)
      shell: ping {{ item }} -c 2
      loop:
        - db.hwx
        - repo.hwx
        - ambari-{{ env_instance }}.hwx
        - os02-{{ env_instance }}.hwx
        - os03-{{ env_instance }}.hwx
        - os04-{{ env_instance }}.hwx
        - os05-{{ env_instance }}.hwx
        - os06-{{ env_instance }}.hwx
        - os07-{{ env_instance }}.hwx
        - os10-{{ env_instance }}.hwx
        - os11-{{ env_instance }}.hwx
        - os12-{{ env_instance }}.hwx
        - os13-{{ env_instance }}.hwx
        - os14-{{ env_instance }}.hwx
        - os15-{{ env_instance }}.hwx
        - os16-{{ env_instance }}.hwx
        - os17-{{ env_instance }}.hwx
        - os18-{{ env_instance }}.hwx
        - os19-{{ env_instance }}.hwx
        # - os20-{{ env_instance }}.hwx
      tags:
        - full
    - name: ping cluster peers (Left)
      shell: ping {{ item }} -c 2
      loop:
        - db.hwx
        - repo.hwx
        - ambari-{{ env_instance }}.hwx
        - os02-{{ env_instance }}.hwx
        - os03-{{ env_instance }}.hwx
        - os04-{{ env_instance }}.hwx
        - os16-{{ env_instance }}.hwx
        - os10-{{ env_instance }}.hwx
        - os11-{{ env_instance }}.hwx
        - os12-{{ env_instance }}.hwx
        - os13-{{ env_instance }}.hwx
        - os14-{{ env_instance }}.hwx
        - os15-{{ env_instance }}.hwx
      tags:
        - left
    - name: ping cluster peers (Right)
      shell: ping {{ item }} -c 2
      loop:
        - db.hwx
        - repo.hwx
        - ambari-{{ env_instance }}.hwx
        - os05-{{ env_instance }}.hwx
        - os06-{{ env_instance }}.hwx
        - os07-{{ env_instance }}.hwx
        - os16-{{ env_instance }}.hwx
        - os17-{{ env_instance }}.hwx
        - os18-{{ env_instance }}.hwx
        - os19-{{ env_instance }}.hwx
      tags:
        - right
