- hosts: os
  become: true

  tasks:
    - name: Copy Docker Daemon Config to Cluster Hosts
      copy:
        src: /Users/dstreev/projects/david/hwx-ansible/infrastructure/docker/daemon.json
        dest: /etc/docker/daemon.json
        owner: root
        mode: 0644
    - name: Restart Docker
      systemd:
        name: docker
        state: reloaded
