version: '3.6'
services:
  ambari:
    hostname: ambari-${ENV_INSTANCE}.hwx
    image: dstreev/centos7_sshd:${IMAGE_TAG}
    ports:
      - target: 22
        published: 220${ENV_INSTANCE}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hdpdata
        target: /hadoop
      - type: volume
        source: hdplog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hdp_base:
        aliases:
          - ambari-${ENV_INSTANCE}.hwx
    deploy:
      placement:
        constraints:
          - node.labels.hdp.ambari == true

  os04:
    hostname: os04-${ENV_INSTANCE}.hwx
    image: dstreev/centos7_sshd:${IMAGE_TAG}
    ports:
      - target: 22
        published: 220${ENV_INSTANCE}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hdpdata
        target: /hadoop
      - type: volume
        source: hdplog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hdp_base:
        aliases:
          - os04-${ENV_INSTANCE}.hwx
    deploy:
      placement:
        constraints:
          - node.labels.hdp.host == os04
  os05:
    hostname: os05-${ENV_INSTANCE}.hwx
    image: dstreev/centos7_sshd:${IMAGE_TAG}
    ports:
      - target: 22
        published: 220${ENV_INSTANCE}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hdpdata
        target: /hadoop
      - type: volume
        source: hdplog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hdp_base:
        aliases:
          - os05-${ENV_INSTANCE}.hwx
    deploy:
      placement:
        constraints:
          - node.labels.hdp.host == os05
  os06:
    hostname: os06-${ENV_INSTANCE}.hwx
    image: dstreev/centos7_sshd:${IMAGE_TAG}
    ports:
      - target: 22
        published: 220${ENV_INSTANCE}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hdpdata
        target: /hadoop
      - type: volume
        source: hdplog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hdp_base:
        aliases:
          - os06-${ENV_INSTANCE}.hwx
    deploy:
      placement:
        constraints:
          - node.labels.hdp.host == os06
  os13:
    hostname: os13-${ENV_INSTANCE}.hwx
    image: dstreev/centos7_sshd:${IMAGE_TAG}
    ports:
      - target: 22
        published: 220${ENV_INSTANCE}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hdpdata
        target: /hadoop
      - type: volume
        source: hdplog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hdp_base:
        aliases:
          - os13-${ENV_INSTANCE}.hwx
    deploy:
      placement:
        constraints:
          - node.labels.hdp.host == os13
  os14:
    hostname: os14-${ENV_INSTANCE}.hwx
    image: dstreev/centos7_sshd:${IMAGE_TAG}
    ports:
      - target: 22
        published: 220${ENV_INSTANCE}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hdpdata
        target: /hadoop
      - type: volume
        source: hdplog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hdp_base:
        aliases:
          - os14-${ENV_INSTANCE}.hwx
    deploy:
      placement:
        constraints:
          - node.labels.hdp.host == os14
  os15:
    hostname: os15-${ENV_INSTANCE}.hwx
    image: dstreev/centos7_sshd:${IMAGE_TAG}
    ports:
      - target: 22
        published: 220${ENV_INSTANCE}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hdpdata
        target: /hadoop
      - type: volume
        source: hdplog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hdp_base:
        aliases:
          - os15-${ENV_INSTANCE}.hwx
    deploy:
      placement:
        constraints:
          - node.labels.hdp.host == os15
  os16:
    hostname: os16-${ENV_INSTANCE}.hwx
    image: dstreev/centos7_sshd:${IMAGE_TAG}
    ports:
      - target: 22
        published: 220${ENV_INSTANCE}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hdpdata
        target: /hadoop
      - type: volume
        source: hdplog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hdp_base:
        aliases:
          - os16-${ENV_INSTANCE}.hwx
    deploy:
      placement:
        constraints:
          - node.labels.hdp.host == os16

networks:
  hdp_base:
    external: true
    driver: overlay
    attachable: true
volumes:
  hdpdata:
    driver: local
  hdpdata:
    driver: local
  hdplog:
    driver: local
