version: '3.6'
services:
  ambari:
    hostname: ambari-{{ env_instance }}.hwx
    image: dstreev/centos7_sshd:{{ image_tag }}
    privileged: true
    ports:
      - target: 22
        published: 220{{ env_instance }}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hadoop
        target: /hadoop
      - type: volume
        source: hwxlog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hwx:
        aliases:
          - ambari-{{ env_instance }}.hwx
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.labels.hdp.ambari == true

  os04:
    hostname: os04-{{ env_instance }}.hwx
    image: dstreev/centos7_sshd:{{ image_tag }}
    privileged: true
    ports:
      - target: 22
        published: 220{{ env_instance }}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hadoop
        target: /hadoop
      - type: volume
        source: hwxlog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hwx:
        aliases:
          - os04-{{ env_instance }}.hwx
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.labels.hdp.host == os04
  os05:
    hostname: os05-{{ env_instance }}.hwx
    image: dstreev/centos7_sshd:{{ image_tag }}
    privileged: true
    ports:
      - target: 22
        published: 220{{ env_instance }}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hadoop
        target: /hadoop
      - type: volume
        source: hwxlog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hwx:
        aliases:
          - os05-{{ env_instance }}.hwx
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.labels.hdp.host == os05
  os06:
    hostname: os06-{{ env_instance }}.hwx
    image: dstreev/centos7_sshd:{{ image_tag }}
    privileged: true
    ports:
      - target: 22
        published: 220{{ env_instance }}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hadoop
        target: /hadoop
      - type: volume
        source: hwxlog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hwx:
        aliases:
          - os06-{{ env_instance }}.hwx
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.labels.hdp.host == os06
  os13:
    hostname: os13-{{ env_instance }}.hwx
    image: dstreev/centos7_sshd:{{ image_tag }}
    privileged: true
    ports:
      - target: 22
        published: 220{{ env_instance }}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hadoop
        target: /hadoop
      - type: volume
        source: hwxlog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hwx:
        aliases:
          - os13-{{ env_instance }}.hwx
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.labels.hdp.host == os13
  os14:
    hostname: os14-{{ env_instance }}.hwx
    image: dstreev/centos7_sshd:{{ image_tag }}
    privileged: true
    ports:
      - target: 22
        published: 220{{ env_instance }}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hadoop
        target: /hadoop
      - type: volume
        source: hwxlog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hwx:
        aliases:
          - os14-{{ env_instance }}.hwx
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.labels.hdp.host == os14
  os15:
    hostname: os15-{{ env_instance }}.hwx
    image: dstreev/centos7_sshd:{{ image_tag }}
    privileged: true
    ports:
      - target: 22
        published: 220{{ env_instance }}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hadoop
        target: /hadoop
      - type: volume
        source: hwxlog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hwx:
        aliases:
          - os15-{{ env_instance }}.hwx
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.labels.hdp.host == os15
  os16:
    hostname: os16-{{ env_instance }}.hwx
    image: dstreev/centos7_sshd:{{ image_tag }}
    privileged: true
    ports:
      - target: 22
        published: 220{{ env_instance }}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hadoop
        target: /hadoop
      - type: volume
        source: hwxlog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hwx:
        aliases:
          - os16-{{ env_instance }}.hwx
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.labels.hdp.host == os16

networks:
  hwx:
    external: true
    driver: overlay
    attachable: true
volumes:
  hadoop:
    driver: local
  hwxlog:
    driver: local
