version: '3.6'
services:
  db:
    hostname: db.hwx
    image: mariadb:10.2
    ports:
      - target: 3306
        published: 33060
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: mariadb
        target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: hortonworks
      MYSQL_USER: ambari
      MYSQL_PASSWORD: hortonworks
    networks:
      hwx:
        aliases:
          - db.hwx
    deploy:
      mode: global
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.labels.hdp.db == true
  repo:
    hostname: repo.hwx
    image: dstreev/hdp-repo:latest
    ports:
      - target: 80
        published: 38000
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: /var/www/html
        target: /www
    networks:
      hwx:
        aliases:
          - repo.hwx
    deploy:
      mode: global
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.labels.hdp.repo == true
  proxy:
    hostname: proxy.hwx
    image: dstreev/centos7_sshd:108
    ports:
      - target: 22
        published: 22199
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hadoop
        target: /hadoop
      - type: volume
        source: hwxlog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hwx:
        aliases:
          - proxy.hwx
    deploy:
      mode: global
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.labels.hdp.host == os01

networks:
  hwx:
    external: true
    driver: overlay
    attachable: true
    name: hwx
volumes:
  mariadb:
    driver: local
  hadoop:
    driver: local
  hwxlog:
    driver: local
