version: '3.6'
services:
  ambari:
    hostname: ambari-${ENV_INSTANCE}.hwx
    image: dstreev/centos7_sshd:${IMAGE_TAG}
    ports:
      - target: 22
        published: 220${ENV_INSTANCE}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hdpdata
        target: /hadoop
      - type: volume
        source: hdplog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hdp_base:
        aliases:
          - ambari-${ENV_INSTANCE}.hwx
    deploy:
      placement:
        constraints:
          - node.labels.hdp.ambari == true

  os05:
    hostname: os05-${ENV_INSTANCE}.hwx
    image: dstreev/centos7_sshd:${IMAGE_TAG}
    ports:
      - target: 22
        published: 220${ENV_INSTANCE}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hdpdata
        target: /hadoop
      - type: volume
        source: hdplog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hdp_base:
        aliases:
          - os05-${ENV_INSTANCE}.hwx
    deploy:
      placement:
        constraints:
          - node.labels.hdp.host == os05
  os06:
    hostname: os06-${ENV_INSTANCE}.hwx
    image: dstreev/centos7_sshd:${IMAGE_TAG}
    ports:
      - target: 22
        published: 220${ENV_INSTANCE}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hdpdata
        target: /hadoop
      - type: volume
        source: hdplog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hdp_base:
        aliases:
          - os06-${ENV_INSTANCE}.hwx
    deploy:
      placement:
        constraints:
          - node.labels.hdp.host == os06
  os07:
    hostname: os07-${ENV_INSTANCE}.hwx
    image: dstreev/centos7_sshd:${IMAGE_TAG}
    ports:
      - target: 22
        published: 220${ENV_INSTANCE}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hdpdata
        target: /hadoop
      - type: volume
        source: hdplog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hdp_base:
        aliases:
          - os07-${ENV_INSTANCE}.hwx
    deploy:
      placement:
        constraints:
          - node.labels.hdp.host == os07
  os15:
    hostname: os15-${ENV_INSTANCE}.hwx
    image: dstreev/centos7_sshd:${IMAGE_TAG}
    ports:
      - target: 22
        published: 220${ENV_INSTANCE}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hdpdata
        target: /hadoop
      - type: volume
        source: hdplog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hdp_base:
        aliases:
          - os15-${ENV_INSTANCE}.hwx
    deploy:
      placement:
        constraints:
          - node.labels.hdp.host == os15
  os16:
    hostname: os16-${ENV_INSTANCE}.hwx
    image: dstreev/centos7_sshd:${IMAGE_TAG}
    ports:
      - target: 22
        published: 220${ENV_INSTANCE}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hdpdata
        target: /hadoop
      - type: volume
        source: hdplog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hdp_base:
        aliases:
          - os16-${ENV_INSTANCE}.hwx
    deploy:
      placement:
        constraints:
          - node.labels.hdp.host == os16
  os17:
    hostname: os17-${ENV_INSTANCE}.hwx
    image: dstreev/centos7_sshd:${IMAGE_TAG}
    ports:
      - target: 22
        published: 220${ENV_INSTANCE}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hdpdata
        target: /hadoop
      - type: volume
        source: hdplog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hdp_base:
        aliases:
          - os17-${ENV_INSTANCE}.hwx
    deploy:
      placement:
        constraints:
          - node.labels.hdp.host == os17
  os18:
    hostname: os18-${ENV_INSTANCE}.hwx
    image: dstreev/centos7_sshd:${IMAGE_TAG}
    ports:
      - target: 22
        published: 220${ENV_INSTANCE}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hdpdata
        target: /hadoop
      - type: volume
        source: hdplog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hdp_base:
        aliases:
          - os18-${ENV_INSTANCE}.hwx
    deploy:
      placement:
        constraints:
          - node.labels.hdp.host == os18
  os19:
    hostname: os19-${ENV_INSTANCE}.hwx
    image: dstreev/centos7_sshd:${IMAGE_TAG}
    ports:
      - target: 22
        published: 220${ENV_INSTANCE}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hdpdata
        target: /hadoop
      - type: volume
        source: hdplog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hdp_base:
        aliases:
          - os19-${ENV_INSTANCE}.hwx
    deploy:
      placement:
        constraints:
          - node.labels.hdp.host == os19

networks:
  hdp_base:
    external: true
    driver: overlay
    attachable: true
volumes:
  hdpdata:
    driver: local
  hdpdata:
    driver: local
  hdplog:
    driver: local
