version: '3.6'
services:
  ambari:
    hostname: ambari-{{ env_instance }}.hwx
    image: dstreev/centos7_sshd:{{ image_tag }}
    privileged: true
    ports:
      - target: 22
        published: 220{{ env_instance }}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hadoop
        target: /hadoop
      - type: volume
        source: hwxlog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hdp_base:
        aliases:
          - ambari-{{ env_instance }}.hwx
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.labels.hdp.ambari == true

  os05:
    hostname: os05-{{ env_instance }}.hwx
    image: dstreev/centos7_sshd:{{ image_tag }}
    privileged: true
    ports:
      - target: 22
        published: 220{{ env_instance }}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hadoop
        target: /hadoop
      - type: volume
        source: hwxlog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hdp_base:
        aliases:
          - os05-{{ env_instance }}.hwx
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.labels.hdp.host == os05
  os06:
    hostname: os06-{{ env_instance }}.hwx
    image: dstreev/centos7_sshd:{{ image_tag }}
    privileged: true
    ports:
      - target: 22
        published: 220{{ env_instance }}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hadoop
        target: /hadoop
      - type: volume
        source: hwxlog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hdp_base:
        aliases:
          - os06-{{ env_instance }}.hwx
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.labels.hdp.host == os06
  os07:
    hostname: os07-{{ env_instance }}.hwx
    image: dstreev/centos7_sshd:{{ image_tag }}
    privileged: true
    ports:
      - target: 22
        published: 220{{ env_instance }}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hadoop
        target: /hadoop
      - type: volume
        source: hwxlog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hdp_base:
        aliases:
          - os07-{{ env_instance }}.hwx
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.labels.hdp.host == os07
  os15:
    hostname: os15-{{ env_instance }}.hwx
    image: dstreev/centos7_sshd:{{ image_tag }}
    privileged: true
    ports:
      - target: 22
        published: 220{{ env_instance }}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hadoop
        target: /hadoop
      - type: volume
        source: hwxlog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hdp_base:
        aliases:
          - os15-{{ env_instance }}.hwx
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.labels.hdp.host == os15
  os16:
    hostname: os16-{{ env_instance }}.hwx
    image: dstreev/centos7_sshd:{{ image_tag }}
    privileged: true
    ports:
      - target: 22
        published: 220{{ env_instance }}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hadoop
        target: /hadoop
      - type: volume
        source: hwxlog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hdp_base:
        aliases:
          - os16-{{ env_instance }}.hwx
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.labels.hdp.host == os16
  os17:
    hostname: os17-{{ env_instance }}.hwx
    image: dstreev/centos7_sshd:{{ image_tag }}
    privileged: true
    ports:
      - target: 22
        published: 220{{ env_instance }}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hadoop
        target: /hadoop
      - type: volume
        source: hwxlog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hdp_base:
        aliases:
          - os17-{{ env_instance }}.hwx
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.labels.hdp.host == os17
  os18:
    hostname: os18-{{ env_instance }}.hwx
    image: dstreev/centos7_sshd:{{ image_tag }}
    privileged: true
    ports:
      - target: 22
        published: 220{{ env_instance }}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hadoop
        target: /hadoop
      - type: volume
        source: hwxlog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hdp_base:
        aliases:
          - os18-{{ env_instance }}.hwx
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.labels.hdp.host == os18
  os19:
    hostname: os19-{{ env_instance }}.hwx
    image: dstreev/centos7_sshd:{{ image_tag }}
    privileged: true
    ports:
      - target: 22
        published: 220{{ env_instance }}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: hadoop
        target: /hadoop
      - type: volume
        source: hwxlog
        target: /var/log
      - type: bind
        source: /var/lib/sss/pipes/
        target: /var/lib/sss/pipes/
      - type: bind
        source: /var/lib/sss/mc/
        target: /var/lib/sss/mc/
    networks:
      hdp_base:
        aliases:
          - os19-{{ env_instance }}.hwx
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.labels.hdp.host == os19

networks:
  hdp_base:
    external: true
    driver: overlay
    attachable: true
volumes:
  hadoop:
    driver: local
  hwxlog:
    driver: local
