# One of full, left, center, right
env_set:               "full"

# Number between 00-99
env_instance:          13

# Docker Image Tag to use
image_tag:             "105"

# Ambari Repo Version (used to pull the correct vars in ../environment/vars/ambari_?.json)
ambari_major_version:  2.6
ambari_version:        "2.6.2.2"

blueprint:             "NOT_SET"

hadoop_cli_bin_link:   "https://github.com/dstreev/hadoop-cli/releases/download/1.0.7.2.7-bin/hadoop-cli-1.0.7-SNAPSHOT-2.7.tar.gz"
hadoop_cli_version:    "2.7"
ambari_repo:           "http://repo.hwx/repo/ambari/centos7/2.x/updates/2.6.2.2"
ambari_admin_user:     "admin"
ambari_admin_password: "admin"
ranger_host_base:      "os05"
ranger_admin_user:     "admin"
ranger_admin_password: "admin"

hdp_stack:             "HDP"
hdp_stack_version:     "2.6"
hdp_version:           "2.6.5.0"

hdp_repo_id:           "HDP-2.6"
hdp_repo_url:          "http://repo.hwx/repo/HDP/centos7/2.x/updates/2.6.5.0"

hdp_utils_repo_id:     "HDP-UTILS-1.1.0.22"
hdp_utils_repo_url:    "http://repo.home/repo/HDP-UTILS-1.1.0.22/repos/centos7"

hdp_gpl_repo_id:       "HDP-2.6-GPL"
hdp_gpl_repo_url:      "http://repo.hwx/repo/HDP-GPL/centos7/2.x/updates/2.6.5.0"

os_type:               "redhat7"

ldap_primary_host:     "10.0.1.11"
ldap_primary_port:     389
ldap_secondary_host:
ldap_secondary_port:   389

ldap_ssl:              "false"
ldap_user_class:       "posixaccount"
ldap_user_attr:        "uid"
ldap_group_class:      "posixgroup"
ldap_group_attr:       "cn"
ldap_member_attr:      "member"
ldap_dn:               "cn"
ldap_base_dn:          "cn=accounts,dc=streever,dc=local"
ldap_manager_dn:       "uid=admin,cn=users,cn=accounts,dc=streever,dc=local"
ldap_manager_password: "hortonworks"
ldap_referral:         "ignore"
ldap_bind_anonym:      "false"
