- hosts: localhost

  tasks:
    - name: Add deployment
      lineinfile:
        path: '{{ cfg_path }}/readme.md'
        state: present
        insertafter: '---\|--\|---\|---\|---\|--'
        line: '{{ deploy_type }} | *{{ env_instance }}* | {{ env_set }} | [{{ ambari_version }}](http://ambari-{{ env_instance }}.hwx:8080) | {{ hdp_stack_version }} | {{ ansible_date_time.date }} | '
      tags:
        - add
    - name: Remove deployment
      lineinfile:
        path: '{{ cfg_path }}/readme.md'
        state: absent
        regexp: ^\*{{ env_instance }}\*.*
      tags:
        - remove
