- hosts: localhost

  tasks:
    - name: Add deployment
      lineinfile:
        path: /Users/dstreev/projects/david/hwx-ansible/config/readme.md
        state: present
        insertafter: '--\|---\|---\|---\|--'
        line: '*{{ env_instance }}* | {{ env_set }} | [{{ ambari_version }}](http://ambari-{{ env_instance }}.hwx:8080) | {{ hdp_stack_version }} | {{ ansible_date_time.date }} | '
      tags:
        - add
    - name: Remove deployment
      lineinfile:
        path: /Users/dstreev/projects/david/hwx-ansible/config/readme.md
        state: absent
        regexp: ^\*{{ env_instance }}\*.*
      tags:
        - remove
