# Environment
deploy_type:                     swarm|baremetal|k8s

# One of full, left, center, right
env_set:                 "?"

# Number between 00-99
env_instance:            ?

# Docker Image Tag to use
image_tag:               "108"

# Ambari Repo Version (used to pull the correct vars in ../environment/vars/ambari_?.json)
ambari_major_version:    2.7
ambari_version:          "2.7.0.0"

blueprint:               "NOT_SET"

ambari_repo:             "http://repo.hwx/repo/ambari/centos7/2.x/updates/2.7.0.0/"
ambari_admin_user:       "admin"
ambari_admin_password:   ""
ambari_admin_ldap_password: ""

ambari_server:           ""
ambari_port:             "8080"
zookeeper_server:        ""

db_host:                 ""
db_user:                 ""
db_password:             ""
ranger_host_url:         ""
ranger_admin_user:       "admin"
ranger_admin_password:   ""
knox_host_url:           ""
hive_superuser:          "hive"
hive_superuser_password: ""

# Local Service Accounts used to run HWX Services
hdfs_user:               hdfs
yarn_user:               yarn
hive_user:               hive
sqoop_user:              sqoop
druid_user:              druid
spark_user:              spark
livy_user:               livy
hbase_user:              hbase
storm_user:              storm
atlas_user:              atlas
knox_user:               knox
kafka_user:              kafka
mapred_user:             mapred
ambari_qa_user:          ambari-qa
hadoop_group:            hadoop

hdp_stack:               "HDP"
hdp_stack_version:       "3.0"
hdp_version:             "3.0.0.0"

sdlc_user:               dstreev
tpcds_user:              dstreev
tpcds_size_gb:           250

hadoop_cli_bin_link:     "https://github.com/dstreev/hadoop-cli/releases/download/untagged-9efb4983399ed222f2a8/hadoop-cli-2.0.0-SNAPSHOT-3.0.tar.gz"
hadoop_cli_version:      "3.0"

hdp_repo_id:             "HDP-3.0"
hdp_repo_url:            "http://repo.hdp.local/repo/HDP/centos7/3.x/updates/3.0.0.0"

hdp_utils_repo_id:       "HDP-UTILS-1.1.0.22"
hdp_utils_repo_url:      "http://repo.hdp.local/repo/HDP-UTILS-1.1.0.22/repos/centos7"

hdp_gpl_repo_id:         "HDP-3.0-GPL"
hdp_gpl_repo_url:        "http://repo.hdp.local/repo/HDP-GPL/centos7/3.x/updates/3.0.0.0"

os_type:                 "redhat7"

ldap_primary_host:       ""
ldap_primary_port:       389
ldap_secondary_host:
ldap_secondary_port:     389

ldap_ssl:                "false"
ldap_user_class:         "posixaccount"
ldap_user_attr:          "uid"
ldap_group_class:        "posixgroup"
ldap_group_attr:         "cn"
ldap_member_attr:        "member"
ldap_dn:                 "cn"
ldap_base_dn:            ""
ldap_manager_dn:         ""
ldap_manager_password:   ""
ldap_referral:           "ignore"
ldap_bind_anonym:        "false"
