- hosts: hdp
  become: true
  tags:
    - os
  tasks:
    - name: Add Groups
      group:
        name: '{{ item }}'
        state: present
      loop:
        - flintstones
        - gameofthrones
        - starwars
        - hadoop_admin
        - service
    - name: Add Flintstones Users
      user:
        name: '{{ item }}'
        shell: /bin/bash
        groups: hadoop, flintstones
      loop:
        - bammbamm
        - fred
        - wilma
        - barney
        - betty
        - pebbles
        - bedrock
    - name: Add gameofthrones Users
      user:
        name: '{{ item }}'
        shell: /bin/bash
        groups: hadoop, gameofthrones
      loop:
        - arya
        - jonsnow
        - cersei
        - daenerys
        - sansa
        - tyrion
        - winterfell
        - kingslanding
    - name: Add Starwars Users
      user:
        name: '{{ item }}'
        shell: /bin/bash
        groups: hadoop, starwars
      loop:
        - anakin
        - hansolo
        - leia
        - luke
        - padme
        - yoda
        - coruscant
        - tatooine
    - name: Add Service Group Membership
      user:
        name: '{{ item }}'
        shell: /bin/bash
        groups: service
        append: yes
      loop:
        - coruscant
        - tatooine
        - bedrock
        - kingslanding
        - winterfell
- hosts: sdlc
  become: true
  become_user: hdfs
  tags:
    - hdfs

  vars:
    hs2_jdbc_url: jdbc:hive2://{{ zookeeper_server }}:2181/;serviceDiscoveryMode=zooKeeper;zooKeeperNamespace=hiveserver2
    hive_superuser: hive
    hive_superpassword: hive

  tasks:
    - name: Create User Home Directories in hdfs
      shell: hdfs dfs -mkdir -p /user/{{ item }}/datasets/external;hdfs dfs -chown -R {{ item }}:hadoop /user/{{ item }}
      loop:
        - bammbamm
        - fred
        - wilma
        - barney
        - betty
        - pebbles
        - bedrock
        - arya
        - jonsnow
        - cersei
        - daenerys
        - sansa
        - tyrion
        - winterfell
        - kingslanding
        - anakin
        - hansolo
        - leia
        - luke
        - padme
        - yoda
        - coruscant
        - tatooine
      tags:
        - hdp

    - name: Create Private User Database
      shell: /usr/hdp/current/hive-client/bin/beeline -u "{{ hs2_jdbc_url}}" -n {{ hive_superuser }} -p {{ hive_superpassword }} -e "create database if not exists priv_{{ item }} LOCATION '/user/{{ item }}/datasets/internal.db'"
      loop:
        - bammbamm
        - fred
        - wilma
        - barney
        - betty
        - pebbles
        - bedrock
        - arya
        - jonsnow
        - cersei
        - daenerys
        - sansa
        - tyrion
        - winterfell
        - kingslanding
        - anakin
        - hansolo
        - leia
        - luke
        - padme
        - yoda
        - coruscant
        - tatooine
      tags:
        - hdp
