# Install this to support the construction of the DB and Schema,
# after Ambari has been installed.
- hosts:              db_client
  become:             true
  tasks:
    - name:           Add MariaDB repo
      yum_repository:
        name:         MariaDB
        description:  Install MariaDB Repos
        baseurl:      http://yum.mariadb.org/10.2/centos7-amd64
        gpgkey:       https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
        gpgcheck:     1
        state:        present

    - name:           Install MariaDB Client
      yum:
        name:         MariaDB-client
        state:        latest
