
- hosts: os_reset
  become: true
  tasks:
    - name:
      docker_container:
        name: core-{{ ansible_hostname }}
        state : absent

    - name: Core Init
      shell: docker run -it --privileged -P --name core-{{ ansible_hostname }} -d --network home --dns-search=core.local --restart=unless-stopped alpine:latest
