# Assign labels to the hardware docker nodes to assist with component
# placement.
- hosts: docker_manager
  become: true

  tasks:
    - name: Set Labels on the Docker Node
      shell: docker node update --label-add hdp.ambari=true {{ ambari_host }}

    - name: Set Labels on the Docker Node
      shell: docker node update --label-add hdp.db=true {{ db_host }}

    - name: Set Labels on the Docker Node
      shell: docker node update --label-add hdp.repo=true {{ repo_host }}

    - name: Set Labels on the Docker Node
      shell: docker node update --label-add hdp.host={{ item }} {{ item }}.{{ domain }}
      loop:
        - os01
        - os02
        - os03
        - os04
        - os05
        - os06
        - os07
        - os10
        - os11
        - os12
        - os13
        - os14
        - os15
        - os16
        - os17
        - os18
        - os19
        - os20
        - os30
        - os31
        - os32
