# Goal here is to remove logs older than 'x' days.

- hosts: all
  become: true
  vars:
    days_old: 5
    log_dir_base: /var/log

  tasks:
    - name: Clean up old logs
      shell: find {{ log_dir_base }}/{{ item }}* -mtime +{{ days_old }} -exec rm -f {} \;
      ignore_errors: true
      loop:
        - accumulo
        - ambari-agent
        - ambari-server
        - ambari-infra-solr-client
        - ambari-logsearch-logfeeder
        - ambari-metrics-monitor
        - das
        - druid
        - falcon
        - flume
        - hadoop
        - hadoop-hdfs
        - hadoop-mapreduce
        - hadoop-yarn
        - hbase
        - hive
        - hive2
        - hive-hcatalog
        - hst
        - kafka
        - knox
        - oozie
        - ranger
        - smartsense-activity
        - spark
        - spark2
        - sqoop
        - streams-messaging-manager
        - storm
        - zeppelin
        - zookeeper

    - name: Clean up /tmp
      shell: find /tmp/{{ item }}* -mtime +2 -exec rm -f {} \;
      ignore_errors: true
      loop:
        - mgmt_mgmt
      tags:
        - tmp