# Based on: https://docs.cloudera.com/cdp-private-cloud/latest/upgrade-cdh/topics/ug_cm_upgrade_server.html
- import_playbook: ../../devops/db_backup.yaml

- hosts: all
  become: true

  vars:
    cm_repo: http://repo.streever.local/repo/cm7/7.1.3/

  tasks:
    - name: Remove CM Repos
      yum_repository:
        name: cloudera-manager
        state: absent

    - name: Add New CM Repos
      yum_repository:
        name: cloudera-manager
        description: Cloudera Manager
        baseurl: '{{ cm_repo }}'
        gpgcheck: no

    - name: Stop the Cloudera Manager Agents
      service:
        name: cloudera-scm-agent
        state: stopped

- hosts: manager
  become: true

  tasks:
    - name: Stop Cloudera Manager
      service:
        name: cloudera-scm-server
        state: stopped
    - name: Upgrade Cloudera Manager
      yum:
        name: cloudera-manager-server,cloudera-manager-daemons
        state: latest

- hosts: all
  become: true

  tasks:
    - name: Upgrade Cloudera Manager Agents
      yum:
        name: cloudera-manager-agent,cloudera-manager-daemons
        state: latest



